services:
  db:
    image: postgres:17
    container_name: odoo18_db20
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: BBDDusr
      POSTGRES_PASSWORD: BBDDpsswrd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    image: odoo:18.0
    container_name: odoo18_app20
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: BBDDusr
      PASSWORD: BBDDpsswrd
      ODOO_MASTER_PASSWD: BBDDodoo
    volumes:
      - web_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_odoo1820
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: bbdd@odoo.com
      PGADMIN_DEFAULT_PASSWORD: bbdd
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
volumes:
  postgres_data:
  web_data:
  pgadmin_data: